// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Fuers CLI (migrate/db push) die DIREKTE Verbindung nutzen (ohne Pooler) –
  // noetig fuer DDL + die temporaere Shadow-Datenbank. Die App selbst nutzt
  // zur Laufzeit die gepoolte DATABASE_URL ueber einen eigenen Adapter.
  datasource: {
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
